# Generated by Django 4.2.11 on 2024-04-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, unique=True, verbose_name="email address"),
                ),
                ("date_of_birth", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("coupon_code", models.CharField(max_length=100)),
                ("effective_from", models.DateTimeField()),
                ("effective_till", models.DateTimeField()),
                ("discount_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
